package com.fm2apps.warrantyapp.Helpers.Models;

import java.util.Date;

import io.realm.RealmObject;
import io.realm.annotations.PrimaryKey;

/**
 * Created by mohamed on 10/31/2017.
 */

public class ProductModel extends RealmObject {
    @PrimaryKey
    private int Id;
    private String BarCode;
    private Date ExpiryDate;
    private String Name;
    private String Desc;
    private String Image64;
    private String Receipt64;
    private Date DateCreated;
    //public byte[] ImageBytes;

    // Standard getters & setters generated by your IDE…
    public int getId() {
        return Id;
    }

    public void setId(int id) {
        this.Id = id;
    }

    public String getBarCode() {
        return BarCode;
    }

    public void setBarCode(String barCode) {
        this.BarCode = barCode;
    }

    public Date getExpiryDate() {
        return ExpiryDate;
    }

    public void setExpiryDate(Date expiryDate) {
        this.ExpiryDate = expiryDate;
    }

    public String getName() {
        return Name;
    }

    public void setName(String name) {
        this.Name = name;
    }

    public String getDesc() {
        return Desc;
    }

    public void setDesc(String desc) {
        this.Desc = desc;
    }

    public String getImage64() {
        return Image64;
    }

    public void setImage64(String image64) {
        this.Image64 = image64;
    }

    public String getReceipt64() {
        return Receipt64;
    }

    public void setReceipt64(String receipt64) {
        this.Receipt64 = receipt64;
    }

    public Date getDateCreated() {
        return DateCreated;
    }

    public void setDateCreated(Date dateCreated) {
        this.DateCreated = dateCreated;
    }
}
